name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - run: bun i

      - name: Generate Release Note
        run: bunx changelogithub --output GEN_CHANGELOG.md

      - name: Generate Chrome Extension
        run: cd extension && bun run build:prepare && bun run build && bun run pack:crx
        env:
          WEBEXT_PRIVATE_KEY: ${{ secrets.WEBEXT_PRIVATE_KEY }}

      - uses: softprops/action-gh-release@v2
        with:
          body_path: GEN_CHANGELOG.md
          files: |
            lux-extension.crx
